### ISSUE TITLE
Dialog英文单词折行问题

### ISSUE THREAD

**Issue by Realwate** [gmfe/react-mgm#36]
![image](https://user-images.githubusercontent.com/12814045/42677206-a8b02bd0-86ad-11e8-9eb9-d72fadf08882.png)

如图所示，`information`被截断。查看源码发现`.weui-dialog__bd`这个类。
``` css
.weui-dialog__bd {
   /*...*/
    word-wrap: break-word;
    word-break: break-all;
}
```
是否有必要去除这种强制文本换行 `word-break: break-all;`

**UPDATE：**
发现不止Dialog，很多文本显示(如 label)都有类似的问题。
